spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pautas?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 421088

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
    open-in-view: false
